openapi: 3.0.0
info:
  title: Miro-copy API
  description: Contract for the miro board copy
  version: 0.0.1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    post:
      $ref: "./endpoints/auth.yaml#/login"

  /auth/register:
    post:
      $ref: "./endpoints/auth.yaml#/register"

  /auth/refresh:
    post:
      $ref: "./endpoints/auth.yaml#/refresh"

  /boards:
    get:
      $ref: "./endpoints/boards.yaml#/getAllBoards"
    post:
      $ref: "./endpoints/boards.yaml#/createBoard"
  /boards/{id}:
    get:
      $ref: "./endpoints/boards.yaml#/getBoard"
    delete:
      $ref: "./endpoints/boards.yaml#/deleteBoard"
  /boards/{id}/favourite:
    patch:
      $ref: "./endpoints/boards.yaml#/updateBoardName"
  /boards/{id}/rename:
    patch:
      $ref: "./endpoints/boards.yaml#/updateBoardFavourite"